services:
  server:
    dns:
     - 8.8.8.8
     - 8.8.4.4
    build:
      context: .
      target: dev
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
